# Spotify Global Top 50 EDA

```{r}
library(DBI)
library(RPostgres)

library(stringr)

library(ggplot2)
library(maps)
library(dplyr)
library(plotly)

```

## DB Connection + Dataframe Creation

```{r}
# Connect to the database
con <- dbConnect(
  RPostgres::Postgres(),
  dbname = "postgres",
  host = "localhost",
  port = 5432,
  user = "postgres", # in practice, HIDE THIS
  password = "password" # in practice, HIDE THIS
)

# List tables
tables <- dbListTables(con)
print(tables)

# Run a query
tracks <- dbGetQuery(con, "select *
from playlists
join tracks on playlists.track_id=tracks.track_id
join albums on playlists.album_id=albums.album_id
join trackartists ta on playlists.track_id=ta.track_id
join genreartists ga on ta.artist_id=ga.artist_id
join artists on ga.artist_id=artists.artist_id;")

# Clean
names(tracks) <- make.unique(names(tracks)) # remove duplicate cols
tracks$country <- str_remove(tracks$name, "Top 50 - ") # add country column
tracks$country <- str_remove(tracks$country, "Viral 50 - ") # add country column

# Disconnect
dbDisconnect(con)
```

```{r}
View(tracks)
```

## Most Popular Artist Per Country

```{r}

# Group by 'country' and get the most popular 'artist_name' based on 'popularity', breaking ties by 'nbr_of_followers'
most_popular_artist_per_country <- tracks %>%
  group_by(country) %>%
  arrange(desc(popularity), desc(nbr_of_followers)) %>%  # Sort by popularity and then by nbr_of_followers (both in descending order)
  slice(1) %>%  # Select the top entry for each country
  ungroup()


# View the result
View(most_popular_artist_per_country)
print(most_popular_artist_per_country)
```

```{r}

```

## Least Popular Artist Per Country

```{r}

# Group by 'country' and get the least popular 'artist_name' based on 'popularity', breaking ties by 'nbr_of_followers'
least_popular_artist_per_country <- tracks %>%
  group_by(country) %>%
  arrange(popularity, nbr_of_followers) %>%  # Sort by popularity (ascending) and then by nbr_of_followers (ascending)
  slice(1) %>%  # Select the least popular artist for each country
  ungroup()

# View the result
View(least_popular_artist_per_country)
print(least_popular_artist_per_country)
```

```{r}

```
